first task
monuelDePari/Python pull request #1
Opened 2019-10-07 15:52 UTC by monuelDePari

2019-10-07 20:15 UTC, polyakovartem requested changes

2019-10-07 20:15 UTC, polyakovartem commented on Task1_Sum_of_List.py
> +f.generate_random()
https://docs.python.org/3/library/__main__.html

2019-10-07 20:15 UTC, polyakovartem commented on Task1_Sum_of_List.py
> +class Sum_List:
PEP8 violation

2019-10-07 20:15 UTC, polyakovartem commented on Task1_Sum_of_List.py
> +        average = sum / len(some_list)
module random allows to squash all of these into one line

2019-10-13 11:56 UTC, merged

2019-10-15 08:35 UTC, polyakovartem commented on Task1_Sum_of_List.py
> +from pip._vendor.msgpack.fallback import xrange
why do you need this import?

2019-10-15 09:05 UTC, monuelDePari commented
Pycharm underlined it and suggest to import so I did it

вт, 15 жовт. 2019 о 11:35 Artem <notifications@github.com> пише:

> *@polyakovartem* commented on this pull request.
> ------------------------------
>
> In Task1_Sum_of_List.py
> <https://github.com/monuelDePari/Python/pull/1#discussion_r334818451>:
>
> > @@ -0,0 +1,17 @@
> +from pip._vendor.msgpack.fallback import xrange
>
> why do you need this import?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/monuelDePari/Python/pull/1?email_source=notifications&email_token=AMYU7GBRHHAXZCJ3KEYQLS3QOV6GBA5CNFSM4I6GOVDKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCH6CAPA#pullrequestreview-301735996>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMYU7GBJGBYFBOU6J6LAGFDQOV6GBANCNFSM4I6GOVDA>
> .
>